### ISSUE TITLE
つくる

### ISSUE THREAD

**Issue by nohtaray** [nohtaray/tper#1]

**Comment by nohtaray** [comment]
課題サンプル
http://www.intersteno.org/wp-content/uploads/2015/09/TP2015_EN.pdf

**Comment by nohtaray** [comment]
html と css で1ページずつ作って1枚ずつ画像にして Imagemagick に食べさせればいけそう

**Comment by nohtaray** [comment]
画像への変換はサーバサイドでやれるといい
https://www.npmjs.com/package/html2canvas

**Comment by y-kosuge** [comment]
↑できなさそう

**Comment by nohtaray** [comment]
ブラウザじゃないとできなさそうhttps://github.com/nohtaray/tper/commit/1127580f24a42204a2fed73c077fdc7b2a146d21
jsdom と html2canvas をつかった

```
yada@Yada-MBA % node ./test.js
Promise { <rejected> 'No canvas support' }
```

**Comment by nohtaray** [comment]
画像あっぷろーどさせるか

**Comment by nohtaray** [comment]
あ、node-canvas っていうのつかえばいいのかな？

**Comment by nohtaray** [comment]
https://github.com/MrRio/jsPDF

**Comment by nohtaray** [comment]
PDF 生成までブラウザでできた

**Comment by nohtaray** [comment]
https://nohtaray.github.io/tper/

**Comment by nohtaray** [comment]
できた
